name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # paths:
    #   - "client/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd client
          npm ci

      - name: Build
        run: |
          cd client
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          cname: odinbook.bmilcs.com
          publish_dir: ./client/dist
