name: Client Deploy

on:
  push:
    branches:
      - main
    # paths:
    #   - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    env:
      VITE_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies & Build
        run: |
          cd client
          npm ci
          npm run build

  deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
          cname: odinbook.bmilcs.com
          publish_dir: ./client/dist
